# Generated by Django 5.0 on 2024-01-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='default@gmail.com', max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('birthdate', models.DateField()),
                ('apikey', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
