# Generated by Django 5.0 on 2024-01-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='uniqueid',
        ),
    ]
