# Generated by Django 5.0 on 2024-01-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='apikey',
            field=models.CharField(max_length=30),
        ),
    ]
