# Generated by Django 5.0 on 2024-01-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customers_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='apikey',
            field=models.CharField(max_length=64),
        ),
    ]
