# Generated by Django 5.0 on 2024-01-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customers_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.TextField(),
        ),
    ]
