# Generated by Django 5.0 on 2024-01-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customers_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('productid', models.IntegerField()),
                ('useruid', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('sellerid', models.IntegerField()),
                ('sellername', models.CharField(max_length=255)),
            ],
        ),
    ]
