# Generated by Django 5.0 on 2024-02-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_cart_date_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='useruid',
            field=models.CharField(max_length=255),
        ),
    ]
