# Generated by Django 5.0 on 2024-02-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_cart_image_alter_cart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
