# Generated by Django 5.0 on 2024-02-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivertcharge',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
