# Generated by Django 5.0 on 2024-02-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_cart_delivertcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default='2024-02-05'),
        ),
    ]
