# Generated by Django 5.0 on 2024-01-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussinessname', models.CharField(max_length=255)),
                ('uniquekey', models.CharField(max_length=255)),
                ('bussinessemail', models.EmailField(default='abc@gmail.com', max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('gst', models.CharField(max_length=50)),
                ('bussimage', models.ImageField(upload_to='')),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('taluka', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('owneremail', models.EmailField(default='abc@gmail.com', max_length=254)),
                ('ownerphone', models.CharField(max_length=10)),
                ('ownername', models.CharField(max_length=255)),
                ('bankname', models.CharField(max_length=255)),
                ('accno', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=25)),
                ('aadharcard', models.CharField(max_length=20)),
            ],
        ),
    ]
