# Generated by Django 5.0 on 2024-01-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pincode',
            field=models.CharField(default=416602, max_length=6),
        ),
    ]
