# Generated by Django 5.0 on 2024-01-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bussinessname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
