# Generated by Django 5.0 on 2024-01-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_seller_bussinessname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='ownername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
