# Generated by Django 5.0 on 2024-01-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_alter_seller_ownername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.TextField(),
        ),
    ]
