# Generated by Django 5.0 on 2024-02-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_seller_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='bussimage',
        ),
    ]
