# Generated by Django 5.0 on 2024-02-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_remove_seller_bussimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerid', models.CharField(max_length=40)),
                ('banner', models.ImageField(upload_to='')),
            ],
        ),
    ]
