# Generated by Django 5.0 on 2024-01-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('delivertcharge', models.IntegerField()),
                ('sellerid', models.CharField(max_length=255)),
                ('sellername', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('selleremail', models.EmailField(default='abc@gmail.com', max_length=254)),
                ('category', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
                ('image5', models.ImageField(upload_to='')),
            ],
        ),
    ]
