# Generated by Django 5.0 on 2024-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='len_review',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
