# Generated by Django 5.0 on 2024-01-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_len_review_products_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
