# Generated by Django 5.0 on 2024-02-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('taluka', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('landmark', models.CharField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('sellerid', models.CharField(max_length=255)),
                ('sellername', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('approxdelivery', models.DateField(blank=True, null=True)),
                ('payment', models.CharField(max_length=50)),
                ('totalprice', models.IntegerField()),
                ('couriername', models.CharField(max_length=255)),
                ('track', models.JSONField(blank=True, null=True)),
                ('delstatus', models.CharField(max_length=100)),
            ],
        ),
    ]
