# Generated by Django 5.0 on 2024-02-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_placedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='productid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placedorder',
            name='productname',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='placedorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
