# Generated by Django 5.0 on 2024-02-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_placedorder_productid_placedorder_productname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedorder',
            name='track',
        ),
    ]
