# Generated by Django 5.0 on 2024-02-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_placedorder_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='uuid',
            field=models.CharField(default='0000', max_length=255),
        ),
    ]
