# Generated by Django 5.0 on 2024-02-05 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_placedorder_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placedorder',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='productname',
        ),
        migrations.RemoveField(
            model_name='placedorder',
            name='quantity',
        ),
        migrations.AddField(
            model_name='placedorder',
            name='product',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='couriername',
            field=models.CharField(default='courier', max_length=255),
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 5, 14, 40, 34, 397632, tzinfo=datetime.timezone.utc)),
        ),
    ]
