# Generated by Django 5.0 on 2024-02-05 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_placedorder_productid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
