# Generated by Django 5.0 on 2024-02-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_placedorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='delivery',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placedorder',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placedorder',
            name='productid',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placedorder',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='product',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
