# Generated by Django 5.0 on 2024-02-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_placedorder_delivery_placedorder_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='delivery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='delstatus',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
