# Generated by Django 5.0 on 2024-02-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_placedorder_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='date',
            field=models.DateField(),
        ),
    ]
