# Generated by Django 5.0 on 2024-02-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_placedorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default='white', max_length=15),
        ),
        migrations.AddField(
            model_name='products',
            name='country',
            field=models.CharField(default='white', max_length=30),
        ),
        migrations.AddField(
            model_name='products',
            name='payondel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='returndays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='special',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='products',
            name='warrenty',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
