# Generated by Django 5.0 on 2024-02-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_placedorder_reviewstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='uid',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
