# Generated by Django 5.0 on 2024-05-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_review_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='returndays',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
